### ISSUE TITLE
mmap attributes seams to be OS sensitive

### ISSUE THREAD

**Issue by Patochun** [OmarEmaraDev/midi-parser#1]
I have time to test your MIDI parser module. 
mmap seams to have different usage for linux and Windows.

memoryMap = mmap.mmap(f.fileno(), 0, prot = mmap.PROT_READ)
AttributeError: module 'mmap' has no attribute 'PROT_READ'

My internet search here :

https://github.com/cta-observatory/pyeventio/issues/27
https://docs.python.org/3/library/mmap.html

**Comment by OmarEmaraDev** [comment]
Fixed in 7c96ef4.
