### ISSUE TITLE
Can't install Animation Nodes

### ISSUE THREAD

**Issue by pirtoda** [OmarEmaraDev/midi-parser#4]
I have win 10 v 1909 32 bit +blender 2.80 32bit +blender 2.79 (both) 
I download addond Animation Nodes from many palces here and  and from "animation-nodes.com" and from "cgmatter.com"
try in other windows 10 v 1509 
try unistall and install  c++Redistribuable Visual 2015-2019 two times 
all give the same mssage when click to active the addon  "traceback (most recent call last)
![2 80](https://user-images.githubusercontent.com/66679634/84149879-09b6af00-aa59-11ea-86fd-bc4262d3a4fc.jpg)
![2 79](https://user-images.githubusercontent.com/66679634/84149888-0b807280-aa59-11ea-9ca3-61fecd13552e.jpg)

**Comment by OmarEmaraDev** [comment]
Animation Nodes does not support 32bit operating systems.

**Comment by pirtoda** [comment]
thank you
Is there an alternative

**Comment by OmarEmaraDev** [comment]
@pirtoda Not as far as I know.

**Comment by pirtoda** [comment]
I find somone who translat to 32 bit hereµ
https://blender.stackexchange.com/questions/119253
it's working for python 3.5(blender 2.7.8 and 2.7.9) 
but not working in python 3.7 (blender 2.8)

Thanks to you, now I knew what to look for
